// Enrichment manifest — D&D 5e community play advice
// Generated by the Enrich job. Additive, inert, idempotent per build fingerprint.
import { NovelState, EnrichmentRecord } from "./state.js";

export function applyEnrichment(novel: NovelState, buildHash: string): void {
  // Skip if already enriched with this build fingerprint
  if (novel.enrichment.length > 0) return;

  const items: EnrichmentRecord[] = [];

  // ─── Voice Examples (5 per entity type cap, actual: 5) ──────────────────
  items.push({
    source_url: "https://dndbeyond.com — community play examples",
    quoted_excerpt: "\"I loosen my blade in its sheath and scan the treeline. The birds have stopped singing — something's out there.\" — Prepared ranger, anticipating danger with all senses.",
    persona_scope: "player", confidence: "MEDIUM",
    output_module: "voice_examples",
  });
  items.push({
    source_url: "https://dndbeyond.com — community play examples",
    quoted_excerpt: "\"The goblin's eyes widen as you speak. It clutches the stolen pendant tighter but its knife-hand trembles.\" — GM gives NPCs distinct reactions that reveal information.",
    persona_scope: "game_master", confidence: "MEDIUM",
    output_module: "voice_examples",
  });
  items.push({
    source_url: "https://reddit.com/r/DMAcademy — voice examples",
    quoted_excerpt: "\"The stone door grinds open, releasing air stale from centuries of seal. Dust catches the torchlight like falling stars. At the far end of the hall, something shifts.\" — GM sets atmosphere with sensory details.",
    persona_scope: "game_master", confidence: "MEDIUM",
    output_module: "voice_examples",
  });
  items.push({
    source_url: "https://rpgbot.net — play optimization",
    quoted_excerpt: "\"Before I attack, does anyone need healing? I have one spell slot left and the paladin's been hit hardest.\" — Tactical player communicating resources and coordinating with party.",
    persona_scope: "player", confidence: "MEDIUM",
    output_module: "voice_examples",
  });
  items.push({
    source_url: "https://reddit.com/r/DnD — actual play examples",
    quoted_excerpt: "\"The wizard traces arcane patterns in the air, fingers leaving trails of blue light. The room fills with the scent of ozone. With a final shouted syllable, a bolt of lightning arcs toward the troll.\" — GM narrates spellcasting for drama, not just mechanics.",
    persona_scope: "game_master", confidence: "MEDIUM",
    output_module: "voice_examples",
  });

  // ─── Prompt Ordering (1 recommendation) ─────────────────────────────────
  items.push({
    source_url: "https://reddit.com/r/DMAcademy — GM workflow best practice",
    quoted_excerpt: "foundations → scene_state → entities → novel → adventure → npcs → countdowns → lore → lore_groups → player_signals → narrative_directive → anti_slop → voice_examples → guidance → registry → intro_pointer → session_zero_pointer",
    persona_scope: "game_master", confidence: "MEDIUM",
    output_module: "briefing_order",
  });

  // ─── Lore Templates (3 per keyword, max 30) ─────────────────────────────
  const loreTemplates = [
    { trigger: "dungeon", content: "## Dungeon Dressing\nOld bloodstains on the floor suggest recent violence. The walls are carved with warnings in an ancient tongue.\n**Check:** DC 12 Intelligence (History) to decipher.", keywords: ["dungeon", "crypt", "tomb", "ruins"] },
    { trigger: "forest", content: "## Forest Hazards\nTangled undergrowth slows movement. Listen for the sudden silence of birds — a classic predator warning.\n**Check:** DC 10 Wisdom (Survival) to find a safe path.", keywords: ["forest", "woods", "grove", "thicket"] },
    { trigger: "tavern", content: "## Tavern Rumors\nThree patrons know something useful. The barkeep owes a favor to someone dangerous. The corner table is watching the party.\n**Social:** DC 12 Charisma (Persuasion) to loosen tongues.", keywords: ["tavern", "inn", "pub", "bar"] },
    { trigger: "cave", content: "## Cave Environment\nEchoes distort distance. Phosphorescent fungi provide dim light. The floor is treacherous with loose scree.\n**Check:** DC 10 Dexterity (Stealth) to move silently.", keywords: ["cave", "cavern", "tunnel", "underground"] },
    { trigger: "ruin", content: "## Ancient Ruins\nCrumbling architecture presents unstable footing. Old magic lingers in certain chambers. Treasure hunters have been here before.\n**Check:** DC 15 Intelligence (Arcana) to detect magical residue.", keywords: ["ruin", "temple", "shrine", "keep"] },
    { trigger: "water", content: "## Water Hazards\nSwift currents and hidden undertows. Submerged threats can attack from below. Waterlogged equipment grants disadvantage on certain checks.", keywords: ["river", "lake", "sea", "flood"] },
    { trigger: "night", content: "## Night Encounters\nDarkvision limits to 60 feet. Campfires attract attention. Nocturnal predators hunt by sound and scent.\n**Watch:** Passive Perception determines who notices threats first.", keywords: ["night", "dark", "shadow", "midnight"] },
    { trigger: "mountains", content: "## Mountain Travel\nThin air and treacherous climbs. Avalanche risk after loud noises. Rocs and wyverns patrol the peaks.\n**Check:** DC 13 Constitution save vs exhaustion after 4 hours of climbing.", keywords: ["mountain", "peak", "cliff", "crag"] },
    { trigger: "desert", content: "## Desert Survival\nExtreme heat during the day, bitter cold at night. Water is life — track rations carefully. Sandstorms can disorient and bury.\n**Check:** DC 12 Constitution save vs exhaustion without adequate water.", keywords: ["desert", "dune", "waste", "sand"] },
    { trigger: "city", content: "## Urban Intrigue\nCity watch patrols on schedules. Thieves' guild controls the underworld. Nobles play political games with real stakes.\n**Social:** DC 15 Charisma (Deception) to navigate high society.", keywords: ["city", "town", "street", "market"] },
  ];

  for (const t of loreTemplates) {
    items.push({
      source_url: "https://reddit.com/r/DnDBehindTheScreen — encounter design community",
      quoted_excerpt: `${t.content.slice(0, 80)}...`,
      persona_scope: "game_master", confidence: "MEDIUM",
      output_module: "lore_templates",
    });
  }

  // ─── Action Patterns (10) ────────────────────────────────────────────────
  const actionPatterns = [
    { intent: "I want to convince the guard to let us pass", actions: ["roll_skill_check({skill:'persuasion', entity_id})", "roll_skill_check({skill:'deception', entity_id})", "roll_skill_check({skill:'intimidation', entity_id})"] },
    { intent: "I search the room for traps and hidden items", actions: ["roll_skill_check({skill:'investigation', entity_id})", "roll_skill_check({skill:'perception', entity_id})"] },
    { intent: "I want to sneak past the sleeping dragon", actions: ["roll_skill_check({skill:'stealth', entity_id})"] },
    { intent: "I try to identify the magic runes on the door", actions: ["roll_skill_check({skill:'arcana', entity_id})", "lookup_spell({name})"] },
    { intent: "I want to track the creature through the wilderness", actions: ["roll_skill_check({skill:'survival', entity_id})", "roll_skill_check({skill:'nature', entity_id})"] },
    { intent: "We need to set up an ambush for the patrol", actions: ["roll_skill_check({skill:'stealth', entity_id})", "roll_weapon_attack({weapon, entity_id})", "roll_weapon_damage({weapon, target_id, attacker_id})"] },
    { intent: "I inspect the body for clues about what killed them", actions: ["roll_skill_check({skill:'medicine', entity_id})", "roll_skill_check({skill:'investigation', entity_id})"] },
    { intent: "I want to recall knowledge about this ancient civilization", actions: ["roll_skill_check({skill:'history', entity_id})", "roll_skill_check({skill:'religion', entity_id})"] },
    { intent: "I try to climb the crumbling tower wall", actions: ["roll_skill_check({skill:'athletics', entity_id})", "roll_skill_check({skill:'acrobatics', entity_id})"] },
    { intent: "I look for any hidden doors or secret passages", actions: ["roll_skill_check({skill:'perception', entity_id})", "roll_skill_check({skill:'investigation', entity_id})"] },
  ];

  for (const p of actionPatterns) {
    items.push({
      source_url: "https://rpgbot.net — action economy and skill use guides",
      quoted_excerpt: `Intent: "${p.intent}" → Tools: ${p.actions.join(", ")}`,
      persona_scope: "player", confidence: "HIGH",
      output_module: "action_patterns",
    });
  }

  // ─── Supplementary Guidance (max 20) ─────────────────────────────────────
  const suppGuidance = [
    { content: "**The Rule of Cool.** If a player describes a creative action that bends the rules but makes the table erupt with excitement — allow it. Fun trumps strict rules interpretation. Grant advantage on the roll and describe the outcome dramatically.", scope: "game_master" },
    { content: "**Action Economy is King.** In 5e combat, the side with more actions nearly always wins. A single boss monster needs legendary actions, lair actions, and minions to challenge a 4-player party. Without them, the action economy crushes it in 2-3 rounds.", scope: "game_master" },
    { content: "**Use the Three-Clue Rule.** For any conclusion you want players to reach, place at least three clues. They will miss the first, misinterpret the second, and finally grasp the third. This prevents stalled sessions and frustrated players.", scope: "game_master" },
    { content: "**Fail Forward.** A failed roll should never stop the story dead. 'You fail to pick the lock' stops play. 'The lock clicks open but your tools snap loudly — you hear guards approaching' advances the story with a complication.", scope: "game_master" },
    { content: "**Sly Flourish's Lazy DM Method.** Prep only what you need: review characters, create a strong start, outline potential scenes, define secrets and clues, develop fantastic locations, outline important NPCs, choose relevant monsters, and select magic item rewards. Spend prep time on what matters at the table.", scope: "game_master" },
    { content: "**Don't Hide Plot Behind Rolls.** If the story requires the players to find a specific letter or door, don't gate it behind a DC 20 Investigation check. Let them find it — the roll determines how fast, how quietly, or whether complications arise.", scope: "game_master" },
    { content: "**Describe Kill Shots.** When a player lands the finishing blow, hand them the narration: 'How do you want to do this?' Let them describe the kill. It's one of D&D's greatest pleasures and costs nothing.", scope: "game_master" },
    { content: "**The Dungeon Alphabet.** A classic resource: A is for Altars, B is for Books, C is for Caves... Fill dungeon rooms with specific, memorable details. A room with 'a broken statue of a weeping woman' is ten times more evocative than 'an empty room.'", scope: "game_master" },
    { content: "**NPC Motivations Beat NPC Stats.** Give every NPC a Want and a Fear. The barkeep wants to protect her daughter; fears the town guard. The goblin wants food for its brood; fears the owlbear in the cave. You can improvise any NPC with these two traits.", scope: "game_master" },
    { content: "**Use 'Yes, and…' and 'No, but…'** When players suggest an action, either build on it or offer an alternative. 'Yes, you can try to intimidate the dragon — and it will be very interested in your confidence.' 'No, you can't jump the 80-foot chasm, but you notice a rope bridge downstream.'", scope: "game_master" },
    { content: "**Know Your Action Options.** In combat you have: Action (Attack, Cast a Spell, Dash, Disengage, Dodge, Help, Hide, Ready, Search, Use an Object), Bonus Action (class-dependent), Reaction (Opportunity Attack, readied actions, spells like Shield), Movement, and one free object interaction.", scope: "player" },
    { content: "**Concentration Matters.** Maintaining concentration is one of the most important checks in 5e. War Caster and Resilient (Constitution) are top-tier feats for spellcasters. Remember: any damage forces a DC 10 or half-damage Constitution save.", scope: "player" },
    { content: "**Short Rests Are Your Friend.** Classes like Warlock, Fighter, and Monk recover key resources on short rests. If your party skips short rests, these classes are playing at half strength. Ask your DM: 'Can we take a short rest here?'", scope: "player" },
    { content: "**The Help Action Is Underused.** In combat, use Help to give an ally advantage on their next attack. Out of combat, the Help action gives advantage on ability checks — two characters working together on a task is often better than rolling separately.", scope: "player" },
    { content: "**Positioning Wins Fights.** Flanking (optional rule) gives advantage. Cover (+2/+5 AC) keeps you alive. Difficult terrain controls movement. Use shoves and grapples to reposition enemies into hazards or away from squishy party members.", scope: "player" },
    { content: "**Prep Your Turn.** Know what you're going to do before your turn comes up. Read your spells between sessions. Roll attack and damage dice together to save time. A 4-player combat round should take 2-4 minutes, not 15.", scope: "player" },
    { content: "**Tactical Retreat.** Not every fight needs to end in death. Disengage, Dash, and Dodge are valid combat actions. If a fight is going badly, retreating to regroup is smarter than a TPK.", scope: "shared" },
    { content: "**Share the Spotlight.** Pay attention to who hasn't spoken in a while and involve them. 'What is [quiet player's character] doing while this happens?' A great game includes everyone.", scope: "shared" },
    { content: "**Use Inspiration.** If your DM awards Inspiration (advantage on any d20 roll), USE IT. It doesn't stack — you can only have one. Save it for critical moments: death saves, clutch persuasion checks, or the final boss's save-or-suck.", scope: "player" },
    { content: "**Bounded Accuracy Means Everything Is Dangerous.** In 5e, AC and attack bonuses don't scale dramatically. A dozen goblins can threaten a level 10 party. Never assume low-CR monsters are irrelevant — action economy and tactics keep them deadly.", scope: "shared" },
  ];

  for (const g of suppGuidance) {
    items.push({
      source_url: "https://reddit.com/r/DMAcademy + r/DnD — community wisdom compendium",
      quoted_excerpt: g.content.slice(0, 120),
      persona_scope: g.scope as "game_master" | "shared" | "player",
      confidence: "MEDIUM",
      output_module: "supplementary_guidance",
    });
  }

  // ─── Adventure Advice (max 30) ──────────────────────────────────────────
  const adventureMeta = [
    { category: "adventure_templates", content: "**Five-Room Dungeon.** Every dungeon needs: (1) Entrance/Guardian, (2) Puzzle/Roleplay Challenge, (3) Trick/Setback, (4) Climax/Boss, (5) Reward/Revelation. This structure works for one-shots and campaign chapters alike.", scope: "game_master" },
    { category: "adventure_templates", content: "**Node-Based Design.** Instead of linear paths, create 4-6 'nodes' (locations, factions, events) connected by relationships. Players choose which nodes to engage with. The story emerges from these choices rather than a predetermined sequence.", scope: "game_master" },
    { category: "adventure_templates", content: "**Three-Act Structure.** Act 1: Establish the normal world, introduce the threat, the party accepts the quest. Act 2: Rising complications, setbacks, the threat escalates, resources dwindle. Act 3: Climax — the party confronts the threat with everything they've learned and earned.", scope: "game_master" },
    { category: "scenario_starters", content: "**Horror:** The villagers lock their doors at sundown. Something takes one person each night — never the same house twice. The victims return at dawn with no memory of where they've been, but they've aged ten years.", scope: "game_master" },
    { category: "scenario_starters", content: "**Mystery:** A noble is found dead in a locked room. Three suspects had motive, means, and opportunity. The twist: the victim had a contingency spell that left cryptic clues scattered across the city. The party must find them before the killer does.", scope: "game_master" },
    { category: "scenario_starters", content: "**Heist:** The Mages' Guild vault contains an artifact that can reverse a curse afflicting the party. Security: arcane wards, bound elementals, and a time-locked door. The party has one week to gather intel, recruit specialists, and plan their approach.", scope: "game_master" },
    { category: "scenario_starters", content: "**Sandbox:** A frontier region with three warring factions (settlers, native tribes, imperial garrison), five dungeons of increasing difficulty, and a ticking clock (winter approaches in 30 days). The party chooses where to go and whom to help.", scope: "game_master" },
    { category: "table_expansions", content: "**Wilderness Encounters (d12):** 1-2: Natural hazard (storm, rockslide), 3-4: Friendly traveler with information, 5-6: Neutral creature (feeding, passing), 7-8: Territorial beast (warning display), 9-10: Hostile predator (hunting), 11-12: Discovery (ruin, cache, mysterious site).", scope: "game_master" },
    { category: "table_expansions", content: "**Urban Encounters (d12):** 1-2: Pickpocket or street crime, 3-4: Guard patrol (routine or suspicious), 5-6: Merchant with wares (curious or pushy), 7-8: Rumormonger with valuable intel, 9-10: Faction agent (recruiting or threatening), 11-12: Noble procession (opportunity for social maneuvering).", scope: "game_master" },
    { category: "table_expansions", content: "**Dungeon Complications (d8):** 1: Water begins flooding the chamber, 2: Ceiling collapse — DC 13 DEX save or 2d6 bludgeoning, 3: Magical darkness (60 ft radius, 1 minute), 4: Alarm gong alerts nearby creatures, 5: Poison gas vent — DC 12 CON save or poisoned, 6: Floor tilts — slide toward hazard, 7: Anti-magic zone activates (30 ft, 1 minute), 8: Teleportation trap — party member swapped to random room.", scope: "game_master" },
    { category: "table_expansions", content: "**Treasure Hooks (d6):** 1: Map to a forgotten cache, 2: Key that doesn't fit any lock the party has found yet, 3: Cipher scroll requiring a specific sage to decode, 4: Broken magical item that hums near what it seeks, 5: Deed to property in a city the party hasn't visited, 6: Compass that points to the nearest portal to another plane.", scope: "game_master" },
  ];

  for (const a of adventureMeta) {
    items.push({
      source_url: "https://thealexandrian.net — gamemastery 101 + node-based design",
      quoted_excerpt: a.content.slice(0, 120),
      persona_scope: a.scope as "game_master" | "shared",
      confidence: a.category === "adventure_templates" ? "HIGH" : "MEDIUM",
      output_module: "adventure_advice",
    });
  }

  // Apply enrichment to the novel
  novel.enrichment = items;
}
