/**
 * contract-fingerprint.ts — spec-derived format fingerprints (REQ-420, REQ-423).
 *
 * A package-format fingerprint hashes the package-contract sections
 * (§5.16, §5.17, §6.3, §6.4.2) of the assembled specification; a data-format
 * fingerprint hashes the state-model sections (§7.7, §5.9, §5.19, Appendix Q).
 * Both are computed from `holonovel.md` and baked into the server at build time
 * (see `holonovel/src/generated/contract-fingerprints.ts`), so the host can
 * revalidate installed packages and persisted state against its own current
 * value at startup and after a host update.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { createHash } from "node:crypto";

const root = join(import.meta.dirname, "..", "..");

export interface ContractFingerprints {
  packageFormat: string;
  dataFormat: string;
}

// REQ-420 — the sections that determine what a ruleset package contains and how
// it is built. §5.18 (where the entry-point REQs live) is deliberately excluded:
// it names the rebuild/migrate tooling, not the package artifact shape.
const PACKAGE_SECTIONS = ["### 5.16 ", "### 5.17 ", "### 6.3 ", "### 6.4.2 "];

// REQ-423 — the sections that determine the shape of persisted user data.
const DATA_SECTIONS = ["### 7.7 ", "### 5.9 ", "### 5.19 ", "## Appendix Q:"];

function extractSection(text: string, heading: string): string {
  const lines = text.split("\n");
  const startIdx = lines.findIndex((l) => l.startsWith(heading));
  if (startIdx < 0) return "";
  const level = (heading.match(/^#+/) ?? [""])[0].length;
  const out: string[] = [lines[startIdx]];
  for (let i = startIdx + 1; i < lines.length; i++) {
    const m = lines[i].match(/^(#{1,6})\s/);
    if (m && m[1].length <= level) break;
    out.push(lines[i]);
  }
  return out.join("\n").trim();
}

function hashSections(text: string, headings: string[]): string {
  const h = createHash("sha256");
  for (const heading of headings) {
    h.update(heading);
    h.update("\n");
    h.update(extractSection(text, heading));
    h.update("\n");
  }
  return h.digest("hex");
}

export function computeContractFingerprints(specText: string): ContractFingerprints {
  return {
    packageFormat: hashSections(specText, PACKAGE_SECTIONS),
    dataFormat: hashSections(specText, DATA_SECTIONS),
  };
}

export function readAndCompute(specPath?: string): ContractFingerprints {
  const target = specPath ?? join(root, "holonovel.md");
  return computeContractFingerprints(readFileSync(target, "utf-8"));
}

// Write the generated server module. Called by build-order after assemble so the
// server always carries fingerprints matching the current assembled spec.
export function regenerateContractFingerprints(specPath?: string): ContractFingerprints {
  const fp = readAndCompute(specPath);
  const genDir = join(root, "holonovel", "src", "generated");
  mkdirSync(genDir, { recursive: true });
  const body = [
    "// Generated by scripts/lib/contract-fingerprint.ts — do not edit by hand.",
    "// Regenerated by build-order whenever the spec changes.",
    `export const PACKAGE_FORMAT = "${fp.packageFormat}";`,
    `export const DATA_FORMAT = "${fp.dataFormat}";`,
    "",
  ].join("\n");
  writeFileSync(join(genDir, "contract-fingerprints.ts"), body);
  return fp;
}
