#!/usr/bin/env bash
# spec-queue-execute.sh — Phase 3: apply a research plan to holonovel.md.
# Reads .holonovel-state/queue-plans/item-<N>-output.txt, verifies plan
# delimiters, and launches an opencode build session to apply all changes.
# Includes an AAR-based retry loop: if the first attempt fails and produces
# an after-action report, a recovery session is launched to fix the issue
# before retrying. Maximum 3 execute attempts (§6.5 convergence budget).
#
# Usage:
#   ./scripts/spec-queue-execute.sh <item-number> [--dry-run]

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PLANS_DIR="$PROJECT_DIR/.holonovel-state/queue-plans"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# ── args ──────────────────────────────────────────────────────────────────

ITEM="${1:-}"
DRY_RUN=false
[[ "${2:-}" == "--dry-run" ]] && DRY_RUN=true

if [[ -z "$ITEM" ]]; then
  echo -e "${RED}Usage: $0 <item-number> [--dry-run]${NC}"
  exit 1
fi

PLAN_FILE="$PLANS_DIR/item-${ITEM}-output.txt"
if [[ ! -f "$PLAN_FILE" ]]; then
  echo -e "${RED}Plan file not found: $PLAN_FILE${NC}"
  exit 1
fi

# ── validate plan ─────────────────────────────────────────────────────────

if ! grep -q "PLAN_BEGIN" "$PLAN_FILE"; then
  echo -e "${RED}Plan file missing PLAN_BEGIN marker: $PLAN_FILE${NC}"
  exit 1
fi

if ! grep -q "PLAN_END" "$PLAN_FILE"; then
  echo -e "${RED}Plan file missing PLAN_END marker: $PLAN_FILE${NC}"
  exit 1
fi

CHANGE_COUNT=$(grep -c "<!-- CHANGE_BEGIN" "$PLAN_FILE" || true)
echo -e "${GREEN}Plan file valid:${NC} $CHANGE_COUNT change(s) detected"

if $DRY_RUN; then
  echo -e "${YELLOW}Dry run — would execute $CHANGE_COUNT change(s)${NC}"
  exit 0
fi

# ── helpers ───────────────────────────────────────────────────────────────

EXEC_OUT="$PLANS_DIR/item-${ITEM}-execute-output.txt"
EXEC_LOG="$PLANS_DIR/item-${ITEM}-execute-log.txt"
RECOVERY_OUT="$PLANS_DIR/item-${ITEM}-recovery-output.txt"
RECOVERY_LOG="$PLANS_DIR/item-${ITEM}-recovery-log.txt"

has_aar() {
  grep -qiE "after.action.report|after-action|## After Action" "$EXEC_OUT" 2>/dev/null
}

run_execute_session() {
  local label="$1"
  echo -e "${YELLOW}Launching build session ($label)...${NC}"

  local prompt="Apply every \`### Change N:\` block in the attached plan file
($(basename "$PLAN_FILE")) to the specification. Use the exact prose in each
\`**Prose:**\` block — that text replaces or inserts into the appropriate
\`spec/\` source file as specified by the \`**File:**\` directive.

After each change, run \`npm run check\`. If any check fails, stop immediately
and report the failing change and the error output. If all checks pass, report
a summary: which changes were applied, any REQ numbers added, and new test IDs.

Do NOT commit. Edit the canonical spec source files in \`spec/\` (NOT the
assembled \`holonovel.md\` — it is regenerated by \`npm run assemble\`).
After all changes, run \`npm run assemble\` then \`npm run check\`.
If a change must touch files outside \`spec/\`, flag it and stop — the plan
may need revision.

After all changes are applied, run the after-action-report skill and include
a structured AAR in your output. The AAR must cover: what was planned, what
happened, any unexpected issues, and verification results. The AAR block is
required — it enables automated recovery if something goes wrong.

End with: \"ALL CHANGES APPLIED.\" followed by the AAR block."

  set +e
  opencode run \
    "$prompt" \
    --agent build \
    --auto \
    --title "spec-execute-${ITEM}" \
    --dir "$PROJECT_DIR" \
    --file "$PLAN_FILE" \
    > "$EXEC_OUT" 2> "$EXEC_LOG"
  local rc=$?
  set -e

  if [[ $rc -eq 0 ]] && grep -q "ALL CHANGES APPLIED" "$EXEC_OUT" 2>/dev/null; then
    echo -e "${GREEN}Execute: DONE${NC}"
    return 0
  fi

  echo -e "${RED}Execute: FAILED (exit $rc)${NC}"
  return 1
}

run_recovery_session() {
  echo ""
  echo -e "${YELLOW}AAR found — launching recovery session...${NC}"

  local recovery_prompt="The previous execution attempt for item $ITEM failed.
Read the after-action report in the attached execute output file
($(basename "$EXEC_OUT")). Identify what went wrong and apply a targeted fix.

Constraints:
- Fix only the issue described in the AAR. Do not make unrelated changes.
- Run \`npm run check\` after applying the fix.
- Edit spec source files in \`spec/\` (NOT \`holonovel.md\` — it is assembled).
  When the AAR identifies a root cause in a different file, edit that file.
- Do NOT commit.

End with: \"RECOVERY COMPLETE.\" if the fix was applied successfully.
End with: \"RECOVERY FAILED.\" if the issue cannot be fixed automatically
and needs human intervention. Include a brief explanation of what's wrong."

  set +e
  opencode run \
    "$recovery_prompt" \
    --agent build \
    --auto \
    --title "spec-recover-${ITEM}" \
    --dir "$PROJECT_DIR" \
    --file "$EXEC_OUT" \
    > "$RECOVERY_OUT" 2> "$RECOVERY_LOG"
  local rc=$?
  set -e

  if [[ $rc -eq 0 ]] && grep -q "RECOVERY COMPLETE" "$RECOVERY_OUT" 2>/dev/null; then
    echo -e "${GREEN}Recovery: DONE${NC}"
    return 0
  fi

  echo -e "${RED}Recovery: FAILED (exit $rc) — see $RECOVERY_OUT${NC}"
  return 1
}

# ── execute with retry ────────────────────────────────────────────────────

MAX_ATTEMPTS=3  # matches §6.5 convergence budget (3 attempts per metric-targeted step)
echo ""

for ((attempt=1; attempt<=MAX_ATTEMPTS; attempt++)); do
  echo -e "${YELLOW}── Execute attempt $attempt/$MAX_ATTEMPTS ──${NC}"

  # Clear previous output files
  : > "$EXEC_OUT"
  : > "$EXEC_LOG"

  if run_execute_session "attempt $attempt"; then
    exit 0
  fi

  # Check for AAR to enable recovery
  if has_aar; then
    echo -e "${GREEN}AAR detected in output.${NC}"

    if [[ $attempt -lt $MAX_ATTEMPTS ]]; then
      if run_recovery_session; then
        # Recovery succeeded — loop back for another execute attempt
        continue
      fi
      echo -e "${YELLOW}Recovery failed — no further attempts.${NC}"
      break
    fi
  else
    echo -e "${RED}No AAR found — cannot auto-recover.${NC}"
    break
  fi
done

echo -e "${RED}Item $ITEM: all $MAX_ATTEMPTS attempt(s) exhausted.${NC}"
echo "  Execute output: $EXEC_OUT"
echo "  Execute log:    $EXEC_LOG"
echo "  Recovery log:   $RECOVERY_LOG"
exit 1
